#!/bin/sh

###
### 'repo-clean' attempts to remove files not in the
### repository.
###

#
# Use makefile clean commands.
#

echo "Running makefile 'clean' commands."
make clean &> /dev/null
make dist-clean &> /dev/null

#
# List other candidates for removal.
#

echo ""
echo "Other removal candidates (run manually if OK):"
echo ""
find | xargs file | grep "symbolic link" | sed -e 's/:.*//g' | xargs -n 1 -r echo "rm"

#
# Check for the existence of repository resources.
#

if ! which darcs &> /dev/null; then
	echo "*** Cannot find 'darcs'. ***"
	exit
fi

if ! ls _darcs &> /dev/null; then 
	echo "*** Cannot find repository directory '_darcs'.***"
	exit
fi

#
# List ordinary files that the repository doesn't know about.
#

darcs wha -l --boring | grep "^addfile" | sed -e 's/addfile //' | xargs -n 1 -r echo "rm"
darcs wha -l --boring | grep "^adddir" | sed -e 's/adddir //' | xargs -n 1 -r echo "rmdir"

