#!/bin/sh

# Copyright 2006 David Hilvert <dhilvert@auricle.dyndns.org>,
#                              <dhilvert@ugcs.caltech.edu>

#  This file is part of the Anti-Lamenessing Engine.
#
#  The Anti-Lamenessing Engine is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  The Anti-Lamenessing Engine is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Anti-Lamenessing Engine; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

###
### 'repo-clean' attempts to remove files not in the
### repository.
###

#
# Use makefile clean commands.
#

echo ""
echo "Running makefile 'clean' commands."
make clean &> /dev/null
make distclean &> /dev/null

#
# List other candidates for removal.
#

echo ""
echo "Other removal candidates (run manually if OK):"
echo ""
find | xargs file | grep "symbolic link" | sed -e 's/:.*//g' | xargs -n 1 -r echo "rm"

#
# Check for the existence of repository resources.
#

if ! which darcs &> /dev/null; then
	echo "*** Cannot find 'darcs'. ***"
	exit
fi

if ! ls _darcs &> /dev/null; then 
	echo "*** Cannot find repository directory '_darcs'.***"
	exit
fi

#
# List ordinary files that the repository doesn't know about.
#

darcs wha -l --boring | grep "^addfile" | sed -e 's/addfile //' | xargs -n 1 -r echo "rm"
darcs wha -l --boring | grep "^adddir" | sed -e 's/adddir //' | xargs -n 1 -r echo "rmdir"

